### ISSUE TITLE
Filtering commands by Ember version/setting

### ISSUE THREAD

**Issue by chrism** [Exelord/ember-snippets#3]
I find this extension so useful but one thing I find is that I often add the wrong method for the version of Ember I am using.

For example. `init` `⇥` adds

```js
init() {
  this._super(...arguments);
    
},
```
whereas with Octane I would have liked to have added the other `init()` ie

```js
init() {
  super.init(...arguments);
  
}
```

Realise this is entirely my fault but I was wondering if there is there a clever way to tie these commands to the version of Ember I am using to reduce this problem?

**Comment by Exelord** [comment]
VScode does not give an option for that unfortunately :/ But, you can use smart snippets suggestions and teach vscode which snippets you want to use as suggested. Then the not used will be sorted as last.

**Comment by chrism** [comment]
Hi thanks for the explanation thats a shame—will try teaching it via the smart snippets 👍
