### ISSUE TITLE
Octane decorators?

### ISSUE THREAD

**Issue by knownasilya** [Exelord/ember-snippets#6]
Any plans to add support for octane decorators, maybe by reading the edition flag in package.json?

**Comment by Exelord** [comment]
Any examples of which ones do you mean? :)

**Comment by knownasilya** [comment]
@service, @computed (Although not recommended), @action

**Comment by Exelord** [comment]
They are available :) https://github.com/Exelord/ember-snippets/blob/master/docs/javascript/ember/es6/decorators.md#service
